-- 코드를 입력하세요
SELECT A1.FOOD_TYPE, A1.REST_ID, A1.REST_NAME, A1.FAVORITES
FROM REST_INFO AS A1
JOIN(SELECT FOOD_TYPE, MAX(FAVORITES) AS A2_MAX
     FROM REST_INFO
     GROUP BY FOOD_TYPE) AS A2
ON A1.FOOD_TYPE = A2.FOOD_TYPE AND A1.FAVORITES = A2.A2_MAX
ORDER BY FOOD_TYPE DESC