-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A 
    JOIN PATIENT P ON A.PT_NO = P.PT_NO
    JOIN DOCTOR D ON MDDR_ID = DR_ID
WHERE APNT_CNCL_YN = 'N'
    AND A.MCDP_CD = 'CS'
    AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD

