SELECT E.EMP_NO, E.EMP_NAME, G.GRADE,
        CASE WHEN G.GRADE = 'S' THEN SAL*0.2
        WHEN G.GRADE = 'A' THEN SAL*0.15
        WHEN G.GRADE = 'B' THEN SAL*0.1
        ELSE 0 END AS BONUS
FROM HR_EMPLOYEES E
JOIN (SELECT EMP_NO, 
    IF(AVG(SCORE) >= 96, 'S',
      IF(AVG(SCORE) >= 90, 'A',
        IF(AVG(SCORE) >= 80, 'B', 'C'))) AS GRADE
      FROM HR_GRADE
     GROUP BY EMP_NO, YEAR) G
ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO