-- 코드를 입력하세요
SELECT B.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
    INNER JOIN(
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC LIMIT 1) AS A
    ON R.MEMBER_ID = A.MEMBER_ID
    LEFT JOIN MEMBER_PROFILE B
    ON R.MEMBER_ID = B.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT