SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
    CASE
        WHEN STATUS REGEXP('SALE') THEN '판매중'
        WHEN STATUS REGEXP('RESERVED') THEN '예약중'
        WHEN STATUS REGEXP('DONE') THEN '거래완료'
    END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05' 
ORDER BY BOARD_ID DESC;
